name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  typecheck:
    runs-on: buildjet-32vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn typecheck
      - run: yarn build
  test-functions:
    runs-on: buildjet-32vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - run: pwd
      - run: cd ./functions
      - run: pwd
      - run: yarn run build
      - run: yarn run test
